# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  rspec:
    env:
      DATABASE_URL: postgres://test:test@localhost/fountainpencompanion_test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install correct Node version
      uses: actions/setup-node@v2
      with:
        node-version: '12.13.0'
    - name: Install correct Yarn version
      run: npm install yarn@1.22.10 -g
    - name: Set up Postgres
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '12' 
        postgresql db: fountainpencompanion_test
        postgresql user: test
        postgresql password: test      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Install JS dependencies
      run: yarn install
    - name: Run tests
      run: bundle exec rake
    - name: Report to Coveralls (parallel)
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage/lcov/fountainpencompanion.lcov
        parallel: true
        flag-name: rspec
  jest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install correct Node version
      uses: actions/setup-node@v2
      with:
        node-version: '12.13.0'
    - name: Install correct Yarn version
      run: npm install yarn@1.22.10 -g
    - name: Install JS dependencies
      run: yarn install
    - name: Run tests
      run: yarn jest
    - name: Report to Coveralls (parallel)
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage/lcov.info
        parallel: true
        flag-name: jest

  finish:
    needs: [rspec, jest]
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
